### ISSUE TITLE
Should default slippage be 1%, 0%, or something else?

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/ilp-protocol-paystream#15]
When the sockets connect, they send one chunk just to figure out the exchange rate. Every subsequent will have the `minDestinationAmount` set so that the receiver won't accept the chunk if the exchange rate has gotten worse than the original rate by the given `slippage` percentage. The question is what the default slippage should be.

If the default `slippage` is 1%, clients and servers will tolerate the exchange rate getting worse by at most 1% before throwing an error and stopping the flow of money. If we set it to 0% by default, that increases the chances that payments will fail because of legitimate exchange rate movements but also changes the incentive for connectors who might maliciously change the exchange rate. If implementations have zero tolerance by default, changing the exchange rate while a payment is in flight will cause user-level errors that a sneaky connector would not want.

**Comment by sharafian** [comment]
I think 1% is plenty of slippage for the time being. It mainly depends on how long we expect these channels to be open, though. Right now they mostly take a number of seconds, in which case an asset would have to be extraordinarily volatile to move by more than 1% during the lifetime of a socket.

If we want to support long-term sockets that could be open for minutes or hours, maybe we should have a slippage per unit time instead of an absolute maximum slippage for the socket's lifetime

**Comment by emschwartz** [comment]
Alright, we'll go with 1% by default for now but we can change it again later if that seems inappropriate.
